### ISSUE TITLE
从服务器端 获取的是网页啊  怎么解析的啊 

### ISSUE THREAD

**Issue by drduan** [threezj/FuLiApp#2]

**Comment by threezj** [comment]
模M求W，@取html字符串，然後用jsoup提取D片W址。
drduang <notifications@github.com> 於 2016年2月21日，上午11:32 道：


―

**Comment by threezj** [comment]
模拟请求网页，获取html字符串以后，用jsoup库解析字符串，提取图片地址，

**Comment by drduan** [comment]
o  这样啊 长知识了！！ 谢谢
